### ISSUE TITLE
Request the checkpoint trained on the whole dataset

### ISSUE THREAD

**Issue by QUANRJ** [avishkarsaha/translating-images-into-maps#13]
Hi, thanks for your fantastic work.

As mentioned in issue #7 you were going to release the checkpoint trained on the whole Nuscenes dataset. I am writing to request this checkpoint which is important for my recent work. I have tried to train the model on the mini dataset you provided and evaluated it on new images (with close domain with Nuscenes data). However, I got terrible results. Therefore I would like to test the model trained on the whole dataset on these images. (The whole Nuscenes dataset is too large for me to train.)

Thank you again for your work.

Best wishes

**Comment by HaRiZ0s** [comment]
Dear @QUANRJ ,

I agree that it would be very helpful if Avishkar Saha released the checkpoint trained on the whole Nuscenes dataset. Personally I have also trained the model on the mini dataset he provided but it took me 6+ hours and the results weren't great either, IoU's and total loss where far from the optimal. 

My plan is to evaluate it on new images, but I can't figure out how to do it. How did you manage to evaluate it on new images? Could you share your code?

Best Wishes

**Comment by avishkarsaha** [comment]
These have been re-released, apologies for the wait, I didn't realise the link was down.
