### ISSUE TITLE
Pre-trained model to test on unseen images?

### ISSUE THREAD

**Issue by kevinvlowell** [avishkarsaha/translating-images-into-maps#14]
Thanks for the great work! The results look very interesting and I'd love to visualize the prediction outputs of the model on unseen data.

1) Can you release the pre-trained model that was used to get the results in the paper some time soon?
2) How would you produce the example visualizations shown in the paper after passing images through the model?

Thanks again.

**Comment by avishkarsaha** [comment]
The pretrained models have been re-released. 

For visualising, you can follow the code here:
https://github.com/tom-roddick/mono-semantic-maps/blob/master/src/utils/visualise.py
