### ISSUE TITLE
Released checkpoints 

### ISSUE THREAD

**Issue by vnmusat** [avishkarsaha/translating-images-into-maps#19]
Based on the config file of the checkpoints released, I am trying to understand whether the model was pre-trained using a slightly different configuration or a different pre-processing of the dataset.
More specifically, what does the following mean?
"pretrained_model": "pyrocctrandetr_s_0904_100x100_gt100_200down100up_dla64_dice_adam_lr5e5_di3", 
"load_ckpt": "checkpoint-0032.pth.gz"

**Comment by avishkarsaha** [comment]
This meant the model was using a previously trained model of similar configuration. I have now uploaded the trained checkpoints for models trained from scratch.
