### ISSUE TITLE
lmdb.Error

### ISSUE THREAD

**Issue by xibaicai** [avishkarsaha/translating-images-into-maps#22]
lmdb.InvalidError: /mnt/Disk16T/meh/translating-images-into-maps/nuscenes_data/lmdb/samples/CAM_FRONT: MDB_INVALID: File is not an LMDB file。

您在谷歌云盘提供的数据集有些是.icloud后缀，失效。可以重新上传吗？

**Comment by avishkarsaha** [comment]
Hi, I have now provided a new link to the data.
