### ISSUE TITLE
Release of the checkpoints obtained by training on the whole dataset

### ISSUE THREAD

**Issue by Quentin2000** [avishkarsaha/translating-images-into-maps#32]
Hi there, 

Very interesting research, thanks for sharing your work! 

I was wondering when will the checkpoints used to output the results shown in your paper be released? You mentioned a release quite a while ago but I couldn't find it on your iCloud repository. It takes some time to train on the whole dataset, so it would help a lot to start from something already trained.

Thanks a lot!

Quentin

**Comment by avishkarsaha** [comment]
I just updated the link to the pretrained models, should work now!
