### ISSUE TITLE
Can you provide a Google Drive download link? 

### ISSUE THREAD

**Issue by axxx-xxxa** [avishkarsaha/translating-images-into-maps#35]
I am unable to download your pretrained model. Thank you.

**Comment by avishkarsaha** [comment]
I just updated it again, should work now!

**Comment by axxx-xxxa** [comment]
I can't download it from iclouddriver. 
Can you send me an email or use Google Drive to share it with me? 
Thanks.
1149361496@qq.com

**Comment by avishkarsaha** [comment]
Sure, here it is:
https://drive.google.com/drive/folders/11zXPS8_o8Ql7QwnqmUGskwoRsBpBRxNp?usp=sharing

Thanks,
Avi

________________________________
