### ISSUE TITLE
Data is no longer available

### ISSUE THREAD

**Issue by AlaaBenZekri** [avishkarsaha/translating-images-into-maps#38]
Can you please republish the data that you have used as it is no longer available?

**Comment by avishkarsaha** [comment]
It seems to still be working when I look at it? Anyone with the link can view and download?

**Comment by tsoundi** [comment]
Hi @avishkarsaha,

Thank you for your work, I would also like to access the data but I encounter the same issue. 
The folder is unavailable. Is there some way to make it available again?

Kind regards,
tsoundi

**Comment by avishkarsaha** [comment]
This has been updated with a google drive link now!
