### ISSUE TITLE
This nuscenes package can't be imported

### ISSUE THREAD

**Issue by sconlyshootery** [avishkarsaha/translating-images-into-maps#6]
https://github.com/avishkarsaha/translating-images-into-maps/blob/92b9627bef43e9a50f136c13a438a02be9ceebb2/src/data/dataloader.py#L18

**Comment by wang-TJ-20** [comment]
@sconlyshootery @avishkarsaha 您好，请问这个问题解决了吗

**Comment by wang-TJ-20** [comment]
> https://github.com/avishkarsaha/translating-images-into-maps/blob/92b9627bef43e9a50f136c13a438a02be9ceebb2/src/data/dataloader.py#L18
you need pip install nuscenes-devkit
