### ISSUE TITLE
Can you release the checkpoint trained on whole dataset?

### ISSUE THREAD

**Issue by zqh0253** [avishkarsaha/translating-images-into-maps#7]
Thanks for your amazing work!

Do you have any plan to release your checkpoint trained on the whole NuScenes dataset?

**Comment by avishkarsaha** [comment]
Yes, I shall be releasing this in a few weeks.

**Comment by wang-TJ-20** [comment]
@avishkarsaha  hello, can you release your checkpoint trained on the mini-NuScenes dataset? I want to test the accuracy of the code reasoning I reproduced under the mmdetection framework

**Comment by avishkarsaha** [comment]
These have been re-released, apologies for the wait, I didn't realise the link was down.
